[tool.poetry]
name = "todo"
version = "0.1.0"
description = ""
authors = ["CXPhoenix <jate9229@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pynecone = "^0.1.20"
ruff = "^0.0.259"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

